name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "feature/**"]

jobs:
  backend-lint-type-test:
    name: Backend | Lint, Type Check, Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy pytest

      - name: Lint with flake8
        run: flake8 app

      - name: Format check with black
        run: black --check app

      - name: Type check with mypy
        run: mypy app

      - name: Run tests (if any)
        run: pytest || echo "No tests found"

  frontend-format:
    name: Frontend | Format Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Prettier
        run: npm install --global prettier

      - name: Check formatting
        run: prettier --check "**/*.{js,html,css}"

# GitHub Flow recommendations:
# - Use feature branches (feature/branch-name)
# - Open Pull Requests for all changes to main
# - Require PR review and CI passing before merge